### PR TITLE
Added showing trace default on, added --notrace option and removed --trace

### PR DESCRIPTION
**Pull request by adrianzamorski**
I also removed -t option (it was used for --testcase at first, next changed to --trace in one of the pull requests, but not carefully, so I didn't reassign it to --testcase again).

It has also contains changes from pull request nr 47 - https://github.com/TwP/turn/pull/47 .

### CODE REVIEW

**Comment by trans** [comment]
As mentioned before, some code changed recently so this won't merge cleanly. I'll give it a look and see what I can manage incorporating by hand in the latest code, then we can go from there.

Sorry about the inconvenience -- getting the autorunner/runner dichotomy issue fixed was high priority.

**Comment by aspiers** [comment]
Any progress on this?  It fixes issue #66 so would be great to finish the merge.  Thanks!

**Comment by trans** [comment]
Hi Adam,

Thanks for reporting. I'll get to this in the next few days. I have a few other things I need to finish up first.

Also, I encourage you to give [minitap](http://github.com/rubyworks/minitap) w/ [tapout](http://github.com/rubyworks/tapout) a try, as I consider it the "next generation" of test reporting (albeit it is not quite as mature as Turn in some respects yet).

**Comment by aspiers** [comment]
Thanks for the quick reply!  I'll take a peek at those when I get a chance.

**Comment by trans** [comment]
Okay, I think the current repository settles all this. Full backtrace is the default. If you want to limit the number of backtrace lines use the `-b`/`--backtrace` option, e.g. for no backtrace at all:

```
$ turn -b 0
```

When using autorun mode, you can set it instead with the `backtrace` environment variable.

```
$ backtrace=1 ruby test/mytest.rb
```

**Pull request closed without merging**
