### PR TITLE
Add -t or --trace option for display full stacktrace.

### PR DESCRIPTION
**Pull request by yalab**
Hi TwP.

I want to display full stack trace when test is failure or error.
I tried to add the options t or trace to be able to it.

Please consider merge in this fix.

Thanks.

### CODE REVIEW

**Comment by trans** [comment]
Trace looks like a nice improvement. There's also --debug option.

**Comment by yalab** [comment]
I rebase Twp/master and fix option name 'trace' -> 'debug'.
Could you merge in this fix?

**Comment by trans** [comment]
Also, it appears this option is just on the minitest autorunner. Can it be incorporated into all runners?

**Comment by yalab** [comment]
> Also, it appears this option is just on the minitest autorunner. Can it be incorporated into all runners?

I only use minitest, and I want to see all stacktrace, so I write this patch.
But you think all runners all right.
I will try to fix all runners next.

Thanks

**Comment by trans** [comment]
Just too clarify, there are two types of runners. Autorunners are used when we `require "turn"` in tests and do not use the `turn` command to run the tests. The other runners are used when using the `turn` command. The turn command provides additional options that the autorunner do not (such a selecting alternate output formats).

**Pull request closed without merging**
